[project]
name = "dfdiff"
version = "0.8"
description = "Library that utilize the Python to quickly identify the differences between two DataFrame objects."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "openpyxl>=3.1.5",
]
